import { GoogleGenAI, Type, Modality } from "@google/genai";

if (!process.env.API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const dataUrlToBlobParts = (dataUrl: string) => {
  const parts = dataUrl.split(',');
  const mimeType = parts[0].match(/:(.*?);/)?.[1] || 'application/octet-stream';
  const base64Data = parts[1];
  return { base64Data, mimeType };
};

export const analyzeImage = async (imageDataUrl: string): Promise<string[]> => {
  const { base64Data, mimeType } = dataUrlToBlobParts(imageDataUrl);
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-pro',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: mimeType,
              data: base64Data,
            },
          },
          {
            text: `Analyze this product photo. Suggest 4 detailed, distinct prompts to transform it into a professional studio-quality image. Focus on specific styles like 'minimalist', 'cinematic', 'e-commerce white background', and 'dramatic lighting'. Phrase them as direct commands for an image generation AI.`,
          },
        ],
      },
      config: {
        responseMimeType: 'application/json',
        responseSchema: {
          type: Type.ARRAY,
          items: {
            type: Type.STRING,
            description: "A detailed prompt for image transformation."
          }
        }
      }
    });
    const jsonStr = response.text.trim();
    const suggestions = JSON.parse(jsonStr);
    return suggestions;
  } catch (error) {
    console.error("Error analyzing image:", error);
    throw new Error("Failed to get suggestions from AI. Please try again.");
  }
};

export const editImage = async (imageDataUrl: string, prompt: string): Promise<string> => {
  const { base64Data, mimeType } = dataUrlToBlobParts(imageDataUrl);
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: mimeType,
            },
          },
          { text: prompt },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });
    
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        const editedBase64 = part.inlineData.data;
        const editedMimeType = part.inlineData.mimeType;
        return `data:${editedMimeType};base64,${editedBase64}`;
      }
    }
    throw new Error("No image was generated by the model.");

  } catch (error) {
    console.error("Error editing image:", error);
    throw new Error("Failed to edit image. Please check your prompt and try again.");
  }
};

export const generateImage = async (prompt: string): Promise<string> => {
  try {
    const response = await ai.models.generateImages({
      model: 'imagen-4.0-generate-001',
      prompt: prompt,
      config: {
        numberOfImages: 1,
        outputMimeType: 'image/png',
        aspectRatio: '1:1',
      },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const base64ImageBytes = response.generatedImages[0].image.imageBytes;
      return `data:image/png;base64,${base64ImageBytes}`;
    }
    throw new Error("No image was generated by the model.");

  } catch (error) {
    console.error("Error generating image:", error);
    throw new Error("Failed to generate image. Please check your prompt and try again.");
  }
};
